name: "Hello World Docker Action"
description: "Greet someone and give the current time"
inputs:
  who-to-greet:
    description: "The name of the person to greet"
    required: false
    default: "World"
outputs:
  time:
    description: "The current time"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.who-to-greet }}
