name: Test Docker Action

on: [push]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Hello World Docker Action
        uses: ./hello-world-docker-action
        id: hello
        with:
          who-to-greet: "GitHub"

      - name: Output time
        run: echo "The current time is ${{ steps.hello.outputs.time }}"
